function [iqdata] = IQsigGen(sigBW, fs, modType, filterBeta, numSymbols)

OSR = fs/sigBW;

[iqdata, newSampleRate, newNumSymbols, newNumSamples, chMap] = iqmod( ...
    'sampleRate', fs, 'numSymbols', numSymbols, ...
    'data', 'Random', 'modType', modType, 'oversampling', OSR, ...
    'filterType', 'Root Raised Cosine', 'filterNsym', 80, ...
    'filterBeta', filterBeta, 'carrierOffset', 0, 'magnitude', [0], ...
    'quadErr', 0, 'iqskew', 0, 'gainImbalance', 0, 'correction', 0, ...
    'function', 'download', 'channelMapping', [1 1]);
end